CREATE TABLE BOARD(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255)
)

CREATE TABLE LOCATION(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	BOARD_ID INT,
	WEATHER_WOEID INT
)

CREATE TABLE WEATHER(
	WOEID INT AUTO_INCREMENT,
	D DATE,
	TEMP INT,
	TEXT VARCHAR(255)
)